[package]
name = "rusty-dealer"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bridge-deck = {git = "https://github.com/droundy/bridge-cards"}
colored = "2.0.0"
# druid = "0.7.0"
itertools = "0.10.3"

[profile.dev]
rpath = true
